export const divStyle = {
	width: '',
	height: '',
	margin: '',
	marginTop: '',
	marginLeft: '',
	marginRight: '',
	backgroundColor: '',
	border: '',
	borderRadius: '',
	textAlign: '',
	boxShadow: '',
	display: '',
	gridTemplateColumns: '',
	gridTemplateRows: '',
}
