export const inputStyle = {
	width: '',
	height: '',
	margin: '',
	marginTop: '',
	marginLeft: '',
	marginRight: '',
	color: '',
	backgroundColor: '',
	border: '',
	borderRadius: '',
	textAlign: '',
	boxShadow: '',
	padding: '',
}
